name: Build and Test DB Writer Config
on:
  workflow_call:

env:
  APP_IMAGE: keboola/db-writer-config

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
            docker build --target lib-db-writer-config -t ${APP_IMAGE} .
      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${APP_IMAGE}:latest
          outputs: type=docker,dest=/tmp/imageContainer.tar
      - name: Upload image to artifact
        uses: actions/upload-artifact@v3
        with:
          name: imageContainer
          path: /tmp/imageContainer.tar
        
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Install Compose
        uses: ndeloof/install-compose-action@v0.0.1
        with:
          version: latest
          legacy: true
      - name: Docker version
        run: docker -v
      - name: Docker-compose version
        run: docker-compose -v
      - name: Download image from artifact
        uses: actions/download-artifact@v2
        with:
          name: imageContainer
          path: /tmp
      - name: Load image
        run: docker load -i /tmp/imageContainer.tar
      - name: Test
        run: |
          docker-compose run --rm dev-db-writer-config composer ci