name: Build and Test DB Writer Adapter
on:
  workflow_call:

env:
  APP_IMAGE: keboola/db-writer-adapter

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and export
        run: |
            docker build --target lib-db-writer-adapter -t ${APP_IMAGE} .
            docker save ${APP_IMAGE} -o /tmp/db-writer-adapter.tar
      - name: Upload image to artifact
        uses: actions/upload-artifact@v4
        with:
          name: imageContainerDbWriterAdapter
          path: /tmp/db-writer-adapter.tar
        
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Install Compose
        uses: ndeloof/install-compose-action@v0.0.1
        with:
          version: latest
          legacy: true
      - name: Docker version
        run: docker -v
      - name: Docker-compose version
        run: docker-compose -v
      - name: Download image from artifact
        uses: actions/download-artifact@v4
        with:
          name: imageContainerDbWriterAdapter
          path: /tmp
      - name: Load image
        run: docker load -i /tmp/db-writer-adapter.tar
      - name: Test
        run: |
          docker-compose run --rm app-db-writer-adapter composer ci