name: GitHub Actions CI
on: [ push ]
concurrency: ci-${{ github.ref }} # to avoid tag collisions in the ECR

env:
  BRANCH_NAME: ${{ startsWith(github.event_name, 'pull_request') && github.head_ref || github.ref_name }}

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      changedProjects_dbWriterConfig: ${{ steps.check_changes.outputs.changedProjects_dbWriterConfig }}
      changedProjects_dbWriterAdapter: ${{ steps.check_changes.outputs.changedProjects_dbWriterAdapter }}
      changedProjects_dbWriterCommon: ${{ steps.check_changes.outputs.changedProjects_dbWriterCommon }}

    steps:
      - uses: actions/checkout@v3
      - name: Check for changes
        id: check_changes
        run: |
          echo bin/ci-find-changes.sh ${{ env.BRANCH_NAME }} \
            dbWriterConfig:libs/db-writer-config \
            dbWriterAdapter:libs/db-writer-adapter \
            dbWriterCommon:libs/db-writer-common

  build-db-writer-config:
      needs: check-changes
      runs-on: ubuntu-latest
      if: ${{ needs.check-changes.outputs.changedProjects_dbWriterConfig == '1' }}
      steps:
        - name: Print Outputs
          run: |
            echo "${{ needs.check-changes.outputs.changedProjects_dbWriterConfig }}"

  build-db-writer-adapter:
      needs: check-changes
      runs-on: ubuntu-latest
      if: ${{ needs.check-changes.outputs.changedProjects_dbWriterAdapter == '1' }}
      steps:
        - name: Print Outputs
          run: |
            echo "${{ needs.check-changes.outputs.changedProjects_dbWriterAdapter }}"

  build-db-writer-common:
      needs: check-changes
      runs-on: ubuntu-latest
      if: ${{ needs.check-changes.outputs.changedProjects_dbWriterCommon == '1' }}
      steps:
        - name: Print Outputs
          run: |
            echo "${{ needs.check-changes.outputs.changedProjects_dbWriterCommon }}"