name: GitHub Actions CI
on: [ push ]
concurrency: ci-${{ github.ref }} # to avoid tag collisions in the ECR

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      changedProjects_dbWriterConfig: ${{ steps.check_changes.outputs.changedProjects_dbWriterConfig }}
      changedProjects_dbWriterAdapter: ${{ steps.check_changes.outputs.changedProjects_dbWriterAdapter }}
      changedProjects_dbWriterCommon: ${{ steps.check_changes.outputs.changedProjects_dbWriterCommon }}

    steps:
      - uses: actions/checkout@v3
      - name: Check for changes
        id: check_changes
        run: bin/ci-find-changes.sh

  build:
      needs: check-changes
      runs-on: ubuntu-latest
      if: needs.check-changes.outputs.changedProjects_dbWriterConfig == 1
      steps:
        - uses: actions/checkout@v3
        - name: Build db-writer-config
          run: docker-compose build dev-db-writer-config
        - name: Test db-writer-config
          run: docker-compose run --rm dev-db-writer-config composer ci