name: GitHub Actions CI
on: [ push ]
concurrency: ci-${{ github.ref }} # to avoid tag collisions in the ECR

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      changedProjects_dbWriterConfig: ${{ steps.check_changes.outputs.changedProjects_dbWriterConfig }}
      changedProjects_dbWriterAdapter: ${{ steps.check_changes.outputs.changedProjects_dbWriterAdapter }}
      changedProjects_dbWriterCommon: ${{ steps.check_changes.outputs.changedProjects_dbWriterCommon }}

    steps:
      - uses: actions/checkout@v3
      - name: Check for changes
        id: check_changes
        run: |
          source bin/ci-find-changes.sh ondra-libs \
            dbWriterConfig:libs/db-writer-config \
            dbWriterAdapter:libs/db-writer-adapter \
            dbWriterCommon:libs/db-writer-common

  build:
      needs: check-changes
      runs-on: ubuntu-latest
      steps:
        - name: Print Outputs
          run: |
            echo "${{ needs.check-changes.outputs.changedProjects_dbWriterConfig }}"
            echo "${{ env.changedProjects_dbWriterConfig }}"